### ISSUE TITLE
Nitrouse.Io.liteが閉鎖されるらしいです。

### ISSUE THREAD

**Issue by sakasita001** [sproutrb/meetups#12]
7/30にNitrouse.io.proへ完全移行するようです。
以下の文章を読むと、proも今のところはフリーで使えるのでしょうか。
Nitrous Lite will be shut down completely on July 30th, 2015. Nitrous Pro now has an unlimited free tier.

**Comment by KatoAtsue** [comment]
「Nitrous Pro」の無料プランを使ってみましたが、8月以降、終日使用できたのでsprout.rbでも大丈夫だと思います。
（nitorousサイトの英文の理解を誤っているかもしれないので、間違っていたらどなたか修正してください。）

**Comment by ToruKurahashi** [comment]
フリープランは1コンテナ、1GBメモリ、5Gストレージみたいですね。
https://www.nitrous.io/pricing/#standard

**Comment by sakasita001** [comment]
なぜか、うまく登録できませんでした。(フリープランの対象外だとかなんとか言われてしまう。)

また、相談させてください。

**Comment by KatoAtsue** [comment]
倉橋さんどうもありがとうございます。
坂本さん、私も最初は「すでに登録済みです」のようなメッセージが出て登録できませんでしたが、古い方をログアウトしたりいろいろしていたら登録できました。
正しい登録方法は、また皆様が教えてくださると思います。

**Comment by sada** [comment]
Nitrous.IOはサービス終了しましたので閉じます。
