### ISSUE TITLE
Nitous.ioのコードを好きなエディタで書きたい

### ISSUE THREAD

**Issue by YataFumika** [sproutrb/meetups#9]
手順をまとめます。

１．https://www.nitrous.io/desktop から、アプリケーションをダウンロードする。
２．ダウンロードが成功したら、Nitous.ioのID、パスワード(GitHubのものでOK)を入力する
３．ログインに成功すると、Nitous.ioのサーバにあるコードが以下のフォルダにダウンロードされます。
　　Mac: ~/Nitous.io/Box名/ フォルダ以下

■　コードの同期
desttopアプリケーションの「File Sync」をオンにします（クリックすればOK）。
これで、ローカルのコードを変更すると、Nitous.ioサーバのコードも変更されます。
(同期の間隔は不明だが、タイムラグはほぼないみたい）

■ コンソールの立ち上げ
ダウンロードしたアプリケーションの「shell」ボタンをクリックすると、ローカルのコンソールがNitous.ioのコンソールと同じように立ち上がります。
ssh_keyの作成を行おうとするので、パスフレーズを入力し、Enterを押します。
するとコンソールが立ち上がるので、Nitous.ioのコンソールにコマンドを入力するようなイメージで、ローカルからNitous.ioへコマンドを入力できます。

■　サーバの立ち上げ
　Nitous.ioのコンソール（コンソールの立ち上げ手順にて表示したコンソール、あるいはwebからNitous.ioにログインし立ち上げたコンソール）にて、rails sコマンドを使いサーバを立ち上げます。
　サーバのURLは「http://BOX名.apne1.nitrousbox.com/」になります。

■　開発の流れ
「File Sync」をオンにする。
アプリケーションから、Nitous.ioからダウンロードしたコードのあるフォルダを開く。
(Windows: タスクトレイからアプリケーションを右クリックし、それっぽメニューをえらぶ）
コードを好きなエディタで開く。
→開発する！

windowsマニュアル：http://help.nitrous.io/nitrous-desktop-win/

**Comment by sada** [comment]
Nitrous.IOはサービス終了しましたので閉じます。
